BUG: qt/drop_editor: use event filter instead of magic.
This avoid following strange errors when running mayavi under Qt:
  File "/home/pankaj/work/enthought/ETS/traitsui/traitsui/qt4/drop_editor.py", line 71, in init
    (type(self.control), ), dict(_DropWidget.__dict__))
  TypeError: __class__ assignment: only for heap types

This commit replace dynamic base class insertion for drag-drop handling
with a simple EventFilter and also adds import of clipboard which
was being used without importing.